/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bankware.finlab.myworkchain.common;

//import org.junit.Test;

public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//    }
}
